services:
  - type: web
    name: annregar-realty
    runtime: python
    buildCommand: pip install -r requirements.txt
    startCommand: |
      python manage.py migrate &&
      gunicorn test_project.wsgi:application
    staticPublishPath: staticfiles
    envVars:
    - key: DJANGO_SETTINGS_MODULE
      value: test_project.settings
    - key: PYTHON_VERSION
      value: 3.11.8
