# Generated by Django 5.2.4 on 2025-07-29 05:19

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('properties', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='property',
            name='price',
            field=models.TextField(max_length=255),
        ),
    ]
