# Generated by Django 5.2.4 on 2025-07-19 06:14

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('properties', '0003_propertyimage'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='property',
            name='barangay',
        ),
        migrations.RemoveField(
            model_name='property',
            name='city_or_municipality',
        ),
        migrations.RemoveField(
            model_name='property',
            name='image',
        ),
        migrations.RemoveField(
            model_name='property',
            name='province',
        ),
        migrations.RemoveField(
            model_name='property',
            name='region',
        ),
        migrations.AddField(
            model_name='property',
            name='complete_address',
            field=models.CharField(max_length=255, null=True),
        ),
        migrations.AddField(
            model_name='property',
            name='google_maps_link',
            field=models.URLField(blank=True, null=True),
        ),
    ]
