# Generated by Django 5.2.4 on 2025-07-23 06:36

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('properties', '0004_remove_property_barangay_and_more'),
    ]

    operations = [
        migrations.RenameField(
            model_name='property',
            old_name='complete_address',
            new_name='address',
        ),
    ]
